### ISSUE TITLE
Clustering empty

### ISSUE THREAD

**Issue by nitrag** [rmnblm/Mapbox-iOS-Examples#1]
I've followed your clustering example ([here](https://github.com/rmnblm/mapbox-ios-examples/blob/master/src/Examples/ClusteringViewController.swift)) and my mapview is coming up empty (no points). Is there something else that needs to be done outside this file? Like in the map's style itself on Mapbox Studio Editor? Or on `mapView` itself?

Sidenote: trying to clone your example project and get it working but running into difficulties...

**Comment by nitrag** [comment]
Ok, I got your project working, had to convert to Swift 3 and hack swiftyjson to get past a bug. 

Anyway, when you click on Clustering the first time, nothing happens. I waited 30 seconds or so. I go back to the main table view and click on Clustering again, it works almost instantly!

Is this a Mapbox Bug?

**Comment by rmnblm** [comment]
Hi @nitrag 

First, it wasn't necessary to convert SwiftyJSON to Swift 3 by hand. If your CocoaPods version isn't >= 1.1.0 (you can check this with `pod --version`), CocoaPods will install an older version which isn't Swift 3 compatible (I honestly don't know why, but I could fix this by installing a pre-release version of CocoaPods with `sudo gem install cocoapods --pre`). I just checked the SwiftyJSON repo and it seems that @zhigang1992 updated SwiftyJSON a few days ago. I'll check if this problem still exist.

Second, I was not able to reproduce your problem. To answer your question: No, there has nothing to be done outside of the file. On what iPhone with which iOS version are you running the examples? What about the other examples, do they work properly?
It may be a Mapbox bug, let me investigate this further for you.

**Comment by rmnblm** [comment]
Okay, I just tried to do a `pod install` with CocoaPods version 1.0.1 and the problem with SwiftyJSON still occurs, even when it downloads SwiftyJSON 3.1.0.

```
$ pod install
Analyzing dependencies
Fetching podspec for `Mapbox-iOS-SDK` from `https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.4.0-alpha.4/platform/ios/Mapbox-iOS-SDK.podspec`
Downloading dependencies
Installing Mapbox-iOS-SDK (3.4.0-alpha.4)
Installing SwiftyJSON (3.1.0)
Generating Pods project
Integrating client project
```

So it's still required to have a CocoaPods version >= 1.1.0 to install all required dependencies. Also see this issue which addresses this problem: https://github.com/SwiftyJSON/SwiftyJSON/issues/647

**Comment by nitrag** [comment]
Dunno man, now it works fine. Only difference is I upgraded to latests cocoapods.

```
gem install cocoapods --pre
git clone https://github.com/rmnblm/mapbox-ios-examples.git

cd mapbox-ios-examples
pod install
#setup Keys.plist
#open xcworkspace
#change iOS "Team"
#change build target to "iPhone 6"
#build and run
#works!
```

Back to my main issue with not seeing any data. I was calling `loadData()` within `viewDidAppear()`. Not good. Based on another example I switched to use: `func mapViewDidFinishLoadingMap(_ mapView: MGLMapView)` and voila! Loads perfectly well!

**Comment by rmnblm** [comment]
I noticed the [example](https://gist.github.com/boundsj/1a239f5f3e4d27eb7a4fba54db328152) and updated all view controllers in this repo loading the data in the `func mapViewDidFinishLoadingMap(_ mapView: MGLMapView)` function, see commit [here](https://github.com/rmnblm/mapbox-ios-examples/commit/88dbf763d8a4dcecacdb624e552a4232b44a6680).

Maybe the Mapbox Team (@1ec5 or @boundsj) should clarify which method to use when loading map data?

**Comment by 1ec5** [comment]
Yes, we don’t have official examples yet, but `MGLMapViewDelegate.mapViewDidFinishLoadingMap(_:)` is a fine place to put anything that depends on the style being loaded, since the style loads asynchronously. Note also mapbox/mapbox-gl-native#6412, for which we’re planning to add an additional delegate method, probably `MGLMapViewDelegate.mapView(_:didFinishLoadingStyle:)`. Eventually, I think we’ll add an `MGLMapView.setStyle(_:completionHandler:)` method that takes a closure, as described in https://github.com/mapbox/mapbox-gl-native/issues/6386#issuecomment-249033669, but that’s a little ways off.

**Comment by rmnblm** [comment]
As I'm digging more and more into Mapbox on iOS, I can't wait for this feature to be implemented because I totally need this! Some ETA about this feature? 

PS: This feature would partly solve https://github.com/mapbox/mapbox-gl-native/issues/6361 because calling `mapView.style().layer(withIdentifier: "...")` gives me a "EXC_BAD_ACCESS" exception when the styles haven't been initialized yet.
